# name of the software
name: Bricks and Mortar
# licence of the software
license: Apache 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

# list of additional links on the right of the top menu
headerLinks:
#  - title: GitHub
#    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: <i class="fa fa-github"></i> Visit Our GitHub
    url: https://github.com/BricksandMortar/
  - title: Shoulder the Boulder
    url: http://shouldertheboulder.com

# google analytics
analytics:
  account:
  domain:

# github buttons
github:
  user: BricksandMortar
  repo: IdealPostcodes

jekyll-mentions:
  base_url: https://twitter.com

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
