# name of the software
name: Bricks and Mortar
# licence of the software
license: Apache 2.0
licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html

# list of additional links on the right of the top menu
headerLinks:
#  - title: GitHub
#    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title:
    url:

# google analytics
analytics:
  account:
  domain:

# github
github:
  user: BricksandMortar

collections:
  plugins:
    output: true
    defaults:
      image: false

jekyll-mentions:
  base_url: https://twitter.com

url: https://www.bricksandmortarstudio.com   # with the https protocol
enforce_ssl: www.bricksandmortarstudio.com   # without any protocol

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
